/* eslint-disable */
// Translation dictionary for the custom (non-JSONConfig) admin settings page.
// Only "en" and "de" are maintained; all other languages fall back to "en".
systemDictionary = {
    'shutters adapter settings': { en: 'Adapter settings for shutters', de: 'Adaptereinstellungen für shutters' },
    shutters: { en: 'Coverings', de: 'Behänge' },
    shuttersHintText: {
        en: 'Configure your roller shutters, blinds and awnings here. Each card represents one covering; only the fields relevant to its selected system and enabled protection functions are shown.',
        de: 'Hier werden Rolläden, Raffstores und Markisen konfiguriert. Jede Karte repräsentiert einen Behang; es werden nur die Felder angezeigt, die für das gewählte System und die aktivierten Schutzfunktionen relevant sind.',
    },
    scanButtonLabel: { en: 'Scan for coverings', de: 'Nach Rolläden suchen' },
    scanHintText: {
        en: 'Scans connected adapter instances for foreign states with a covering-related role and automatically adds every newly found covering as a new card below (already configured coverings are never added twice). Homematic (including the "Verschluss" enum.functions Gewerk), KNX, Shelly, Zigbee and Zigbee2MQTT are detected with their matching system; everything else falls back to the generic drivers. Adding coverings changes the adapter configuration, so the adapter instance restarts automatically afterwards.',
        de: 'Durchsucht verbundene Adapterinstanzen nach Fremd-States mit einer rolladenbezogenen Rolle und fügt jeden neu gefundenen Rolladen automatisch als neue Karte unten hinzu (bereits konfigurierte Rolläden werden nie doppelt hinzugefügt). Homematic (inkl. des Gewerks "Verschluss"), KNX, Shelly, Zigbee und Zigbee2MQTT werden mit dem passenden System erkannt; alles andere fällt auf die generischen Driver zurück. Das Hinzufügen ändert die Adapterkonfiguration, daher startet die Adapterinstanz danach automatisch neu.',
    },
    id: { en: 'ID', de: 'ID' },
    name: { en: 'Name', de: 'Name' },
    coveringType: { en: 'Covering type', de: 'Behangtyp' },
    coveringTypeRolladen: { en: 'Roller shutter', de: 'Rolladen' },
    coveringTypeRaffstore: { en: 'External venetian blind', de: 'Raffstore' },
    coveringTypeMarkise: { en: 'Awning', de: 'Markise' },
    coveringTypeLamellen: { en: 'Vertical lamella blind', de: 'Lamellenvorhang' },
    driverType: { en: 'System', de: 'System' },
    driverTypeHomematic: { en: 'Homematic (hm-rpc/hm-rega)', de: 'Homematic (hm-rpc/hm-rega)' },
    driverTypeKnx: { en: 'KNX', de: 'KNX' },
    driverTypeShelly: { en: 'Shelly (Cover mode)', de: 'Shelly (Cover-Modus)' },
    driverTypeZigbee: { en: 'Zigbee (ioBroker.zigbee)', de: 'Zigbee (ioBroker.zigbee)' },
    driverTypeZigbee2Mqtt: { en: 'Zigbee2MQTT', de: 'Zigbee2MQTT' },
    driverTypeGenericPosition: { en: 'Generic (position state)', de: 'Generisch (Positions-State)' },
    driverTypeGenericRelay: { en: 'Generic (open/close relay)', de: 'Generisch (Auf/Zu-Relais)' },
    area: { en: 'Area', de: 'Bereich' },
    orientation: { en: 'Orientation (°)', de: 'Ausrichtung (°)' },
    automationEnabled: { en: 'Automation enabled', de: 'Automatik aktiviert' },
    statePosition: { en: 'Position state ID', de: 'Positions-State-ID' },
    statePositionActual: { en: 'Actual position state ID', de: 'Ist-Positions-State-ID' },
    stateOpen: { en: 'Open state ID', de: 'Auf-State-ID' },
    stateClose: { en: 'Close state ID', de: 'Zu-State-ID' },
    stateStop: { en: 'Stop state ID', de: 'Stopp-State-ID' },
    statesSectionTitle: { en: 'Foreign states', de: 'Fremd-States' },
    protectionSectionTitle: { en: 'Protection settings', de: 'Schutzfunktionen' },
    sunProtectionEnabled: { en: 'Sun protection', de: 'Sonnenschutz' },
    sunTargetPercent: { en: 'Sun target %', de: 'Sonnenschutz-Ziel %' },
    sunWindowStart: { en: 'Sun window start', de: 'Sonnenschutz-Fenster Start' },
    sunWindowEnd: { en: 'Sun window end', de: 'Sonnenschutz-Fenster Ende' },
    rainProtectionEnabled: { en: 'Rain protection', de: 'Regenschutz' },
    windProtectionEnabled: { en: 'Wind protection', de: 'Windschutz' },
    frostProtectionEnabled: { en: 'Frost protection', de: 'Frostschutz' },
    doorContactStateId: { en: 'Door contact state ID', de: 'Türkontakt-State-ID' },
    addCoveringButton: { en: '+ Add covering', de: '+ Rolladen hinzufügen' },
    removeButton: { en: 'Remove', de: 'Entfernen' },
    areasHintText: {
        en: 'Configure the daily opening/closing schedule per area here. Times are "HH:MM" (24h); leave empty to skip that action for that day category. Public holidays fall back to the weekend schedule unless a holiday schedule is set.',
        de: 'Hier wird der tägliche Öffnen-/Schließen-Zeitplan pro Bereich konfiguriert. Zeiten im Format "HH:MM" (24h); leer lassen, um diese Aktion für diese Tageskategorie zu überspringen. An Feiertagen gilt ohne eigenen Feiertagsplan automatisch der Wochenendplan.',
    },
    publicHolidayFederalState: { en: 'German federal state (for public holidays)', de: 'Bundesland (für Feiertage)' },
    publicHolidayFederalStateNone: { en: 'Disabled (no public holiday detection)', de: 'Deaktiviert (keine Feiertagserkennung)' },
    publicHolidayFederalStateBW: { en: 'Baden-Württemberg', de: 'Baden-Württemberg' },
    publicHolidayFederalStateBY: { en: 'Bavaria', de: 'Bayern' },
    publicHolidayFederalStateBE: { en: 'Berlin', de: 'Berlin' },
    publicHolidayFederalStateBB: { en: 'Brandenburg', de: 'Brandenburg' },
    publicHolidayFederalStateHB: { en: 'Bremen', de: 'Bremen' },
    publicHolidayFederalStateHH: { en: 'Hamburg', de: 'Hamburg' },
    publicHolidayFederalStateHE: { en: 'Hesse', de: 'Hessen' },
    publicHolidayFederalStateMV: { en: 'Mecklenburg-Vorpommern', de: 'Mecklenburg-Vorpommern' },
    publicHolidayFederalStateNI: { en: 'Lower Saxony', de: 'Niedersachsen' },
    publicHolidayFederalStateNW: { en: 'North Rhine-Westphalia', de: 'Nordrhein-Westfalen' },
    publicHolidayFederalStateRP: { en: 'Rhineland-Palatinate', de: 'Rheinland-Pfalz' },
    publicHolidayFederalStateSL: { en: 'Saarland', de: 'Saarland' },
    publicHolidayFederalStateSN: { en: 'Saxony', de: 'Sachsen' },
    publicHolidayFederalStateST: { en: 'Saxony-Anhalt', de: 'Sachsen-Anhalt' },
    publicHolidayFederalStateSH: { en: 'Schleswig-Holstein', de: 'Schleswig-Holstein' },
    publicHolidayFederalStateTH: { en: 'Thuringia', de: 'Thüringen' },
    areas: { en: 'Areas', de: 'Bereiche' },
    areaName: { en: 'Area name', de: 'Bereichsname' },
    weekdayOpen: { en: 'Weekday open', de: 'Wochentag auf' },
    weekdayClose: { en: 'Weekday close', de: 'Wochentag zu' },
    weekendOpen: { en: 'Weekend open', de: 'Wochenende auf' },
    weekendClose: { en: 'Weekend close', de: 'Wochenende zu' },
    holidayOpen: { en: 'Public holiday open', de: 'Feiertag auf' },
    holidayClose: { en: 'Public holiday close', de: 'Feiertag zu' },
    sunriseOffsetMinutes: {
        en: 'Open relative to sunrise (min, e.g. -30 or +90)',
        de: 'Öffnen relativ zum Sonnenaufgang (Min., z.B. -30 oder +90)',
    },
    sunsetOffsetMinutes: {
        en: 'Close relative to sunset (min, e.g. -30 or +90)',
        de: 'Schließen relativ zum Sonnenuntergang (Min., z.B. -30 oder +90)',
    },
    duskOffsetMinutes: {
        en: 'Close relative to civil dusk (min, ignored if sunset offset is set)',
        de: 'Schließen relativ zum Ende der Dämmerung (Min., wird bei gesetztem Sonnenuntergangs-Versatz ignoriert)',
    },
    sunEventHintText: {
        en: 'Optional: instead of a static close/open time, couple this area to sunrise/sunset/dusk with an offset in minutes (negative = before, positive = after). Requires latitude/longitude to be set (falls back to the system location). Leave empty to use the static times above.',
        de: 'Optional: Statt einer festen Öffnen-/Schließen-Zeit kann dieser Bereich mit einem Minuten-Versatz an Sonnenaufgang/Sonnenuntergang/Dämmerung gekoppelt werden (negativ = vorher, positiv = danach). Erfordert Breiten-/Längengrad (fällt sonst auf den Systemstandort zurück). Leer lassen, um die festen Zeiten oben zu verwenden.',
    },
    addAreaButton: { en: '+ Add area', de: '+ Bereich hinzufügen' },
    weather: { en: 'Weather data', de: 'Wetterdaten' },
    weatherHintText: {
        en: 'Configure the foreign state IDs of your own weather station here. Any value left empty disables the protection functions that need it (an external weather-service fallback is not implemented yet).',
        de: 'Hier werden die Fremd-State-IDs der eigenen Wetterstation eingetragen. Ein leer gelassener Wert deaktiviert die davon abhängigen Schutzfunktionen (ein externer Wetterdienst-Fallback ist noch nicht umgesetzt).',
    },
    weatherSolarRadiation: { en: 'Solar radiation (W/m²) state ID', de: 'Solarstrahlung (W/m²) State-ID' },
    weatherWindSpeed: { en: 'Wind speed (km/h) state ID', de: 'Windgeschwindigkeit (km/h) State-ID' },
    weatherRain: { en: 'Rain (boolean) state ID', de: 'Regen (boolean) State-ID' },
    weatherOutdoorTemp: { en: 'Outdoor temperature (°C) state ID', de: 'Außentemperatur (°C) State-ID' },
    weatherHumidity: { en: 'Humidity (%) state ID', de: 'Luftfeuchte (%) State-ID' },
    thresholds: { en: 'Global thresholds', de: 'Globale Schwellwerte' },
    sunCloseThreshold: { en: 'Sun close threshold (W/m²)', de: 'Sonnenschutz-Schließschwelle (W/m²)' },
    sunOpenThreshold: { en: 'Sun open threshold (W/m²)', de: 'Sonnenschutz-Öffnungsschwelle (W/m²)' },
    windOpenThreshold: { en: 'Wind activate threshold (km/h)', de: 'Windschutz-Auslöseschwelle (km/h)' },
    windCloseAllowedThreshold: { en: 'Wind calm threshold (km/h)', de: 'Windschutz-Ruheschwelle (km/h)' },
    frostThreshold: { en: 'Frost threshold (°C)', de: 'Frostschutz-Schwelle (°C)' },
    groups: { en: 'Groups', de: 'Gruppen' },
    groupsHintText: {
        en: 'Combine multiple coverings for joint control. Member IDs are entered as a comma-separated list of covering IDs.',
        de: 'Fasst mehrere Rolläden für eine gemeinsame Steuerung zusammen. Mitglieder-IDs werden als kommagetrennte Liste von Rolladen-IDs eingetragen.',
    },
    groupMemberIds: { en: 'Member covering IDs (comma-separated)', de: 'Mitglieder-Rolladen-IDs (kommagetrennt)' },
    addGroupButton: { en: '+ Add group', de: '+ Gruppe hinzufügen' },
    scenes: { en: 'Scenes', de: 'Szenen' },
    scenesHintText: {
        en: 'Named presets that drive one or more coverings to specific positions at once. Targets are entered as "coveringId:percent" pairs, comma-separated.',
        de: 'Benannte Vorgabepositionen, die mehrere Rolläden gleichzeitig auf bestimmte Positionen fahren. Ziele werden als kommagetrennte "coveringId:percent"-Paare eingetragen.',
    },
    sceneTargets: { en: 'Targets ("id:percent", comma-separated)', de: 'Ziele ("id:percent", kommagetrennt)' },
    addSceneButton: { en: '+ Add scene', de: '+ Szene hinzufügen' },
};
