/* eslint-disable */
// Translation dictionary for the custom (non-JSONConfig) admin settings page.
// Only "en" and "de" are maintained; all other languages fall back to "en".
systemDictionary = {
    'shutters adapter settings': { en: 'Adapter settings for shutters', de: 'Adaptereinstellungen für shutters' },
    shutters: { en: 'Coverings', de: 'Behänge' },
    shuttersHintText: {
        en: 'Configure your roller shutters, blinds and awnings here. Each card represents one covering; only the fields relevant to its selected system and enabled protection functions are shown.',
        de: 'Hier werden Rolläden, Raffstores und Markisen konfiguriert. Jede Karte repräsentiert einen Behang; es werden nur die Felder angezeigt, die für das gewählte System und die aktivierten Schutzfunktionen relevant sind.',
    },
    scanButtonLabel: { en: 'Scan for coverings', de: 'Nach Rolläden suchen' },
    scanHintText: {
        en: 'Scans connected adapter instances for foreign states with a covering-related role and automatically adds every newly found covering as a new card below (already configured coverings are never added twice). Homematic (including the "Verschluss" enum.functions Gewerk), KNX, Shelly, Zigbee and Zigbee2MQTT are detected with their matching system; everything else falls back to the generic drivers. Adding coverings changes the adapter configuration, so the adapter instance restarts automatically afterwards.',
        de: 'Durchsucht verbundene Adapterinstanzen nach Fremd-States mit einer rolladenbezogenen Rolle und fügt jeden neu gefundenen Rolladen automatisch als neue Karte unten hinzu (bereits konfigurierte Rolläden werden nie doppelt hinzugefügt). Homematic (inkl. des Gewerks "Verschluss"), KNX, Shelly, Zigbee und Zigbee2MQTT werden mit dem passenden System erkannt; alles andere fällt auf die generischen Driver zurück. Das Hinzufügen ändert die Adapterkonfiguration, daher startet die Adapterinstanz danach automatisch neu.',
    },
    id: { en: 'ID', de: 'ID' },
    name: { en: 'Name', de: 'Name' },
    coveringType: { en: 'Covering type', de: 'Behangtyp' },
    coveringTypeRolladen: { en: 'Roller shutter', de: 'Rolladen' },
    coveringTypeRaffstore: { en: 'External venetian blind', de: 'Raffstore' },
    coveringTypeMarkise: { en: 'Awning', de: 'Markise' },
    coveringTypeLamellen: { en: 'Vertical lamella blind', de: 'Lamellenvorhang' },
    driverType: { en: 'System', de: 'System' },
    driverTypeHomematic: { en: 'Homematic (hm-rpc/hm-rega)', de: 'Homematic (hm-rpc/hm-rega)' },
    driverTypeKnx: { en: 'KNX', de: 'KNX' },
    driverTypeShelly: { en: 'Shelly (Cover mode)', de: 'Shelly (Cover-Modus)' },
    driverTypeZigbee: { en: 'Zigbee (ioBroker.zigbee)', de: 'Zigbee (ioBroker.zigbee)' },
    driverTypeZigbee2Mqtt: { en: 'Zigbee2MQTT', de: 'Zigbee2MQTT' },
    driverTypeGenericPosition: { en: 'Generic (position state)', de: 'Generisch (Positions-State)' },
    driverTypeGenericRelay: { en: 'Generic (open/close relay)', de: 'Generisch (Auf/Zu-Relais)' },
    area: { en: 'Plan', de: 'Plan' },
    orientation: { en: 'Orientation (°)', de: 'Ausrichtung (°)' },
    automationEnabled: { en: 'Automation enabled', de: 'Automatik aktiviert' },
    statePosition: { en: 'Position state ID', de: 'Positions-State-ID' },
    statePositionActual: { en: 'Actual position state ID', de: 'Ist-Positions-State-ID' },
    stateOpen: { en: 'Open state ID', de: 'Auf-State-ID' },
    stateClose: { en: 'Close state ID', de: 'Zu-State-ID' },
    stateStop: { en: 'Stop state ID', de: 'Stopp-State-ID' },
    statesSectionTitle: { en: 'Foreign states', de: 'Fremd-States' },
    protectionSectionTitle: { en: 'Protection settings', de: 'Schutzfunktionen' },
    sunProtectionEnabled: { en: 'Sun protection', de: 'Sonnenschutz' },
    sunTargetPercent: { en: 'Sun target %', de: 'Sonnenschutz-Ziel %' },
    sunWindowStart: { en: 'Sun window start', de: 'Sonnenschutz-Fenster Start' },
    sunWindowEnd: { en: 'Sun window end', de: 'Sonnenschutz-Fenster Ende' },
    rainProtectionEnabled: { en: 'Rain protection', de: 'Regenschutz' },
    windProtectionEnabled: { en: 'Wind protection', de: 'Windschutz' },
    frostProtectionEnabled: { en: 'Frost protection', de: 'Frostschutz' },
    doorContactStateId: { en: 'Door contact state ID', de: 'Türkontakt-State-ID' },
    addCoveringButton: { en: '+ Add covering', de: '+ Rolladen hinzufügen' },
    removeButton: { en: 'Remove', de: 'Entfernen' },
    areasHintText: {
        en: 'Configure the daily opening/closing schedule per plan here. Each field is either a plain clock time ("HH:MM", 24h), an offset relative to sunrise (open) / sunset (close) written with a leading "+" (after) or "-" (before) sign as plain minutes (e.g. "-30") or an "HH:MM" duration (e.g. "+01:30") - append "d" (e.g. "-30d") to use civil dawn/dusk instead of the actual sunrise/sunset - or that offset combined with a "!HH:MM" cap time, e.g. "+30!19:00" (30 minutes after sunset, but never later than 19:00 - analogous for opening/sunrise). Leave a field empty to skip that action for that day category. Public holidays fall back to the weekend schedule unless a holiday schedule is set. Individual weekdays can be overridden below the holiday fields. Assign a plan to a covering on the Coverings tab.',
        de: 'Hier wird der tägliche Öffnen-/Schließen-Zeitplan pro Plan konfiguriert. Jedes Feld ist entweder eine feste Uhrzeit ("HH:MM", 24h), ein Versatz relativ zum Sonnenaufgang (Öffnen) bzw. Sonnenuntergang (Schließen) mit führendem "+" (danach) oder "-" (davor) als reine Minuten (z.B. "-30") oder als "HH:MM"-Dauer (z.B. "+01:30") - mit angehängtem "d" (z.B. "-30d") wird statt Sonnenaufgang/-untergang die Dämmerung verwendet - oder dieser Versatz kombiniert mit einer "!HH:MM"-Obergrenze, z.B. "+30!19:00" (30 Minuten nach Sonnenuntergang, spätestens jedoch 19:00 - sinngemäß auch für Öffnen/Sonnenaufgang). Feld leer lassen, um diese Aktion für diese Tageskategorie zu überspringen. An Feiertagen gilt ohne eigenen Feiertagsplan automatisch der Wochenendplan. Einzelne Wochentage können unterhalb der Feiertagsfelder überschrieben werden. Einem Behang wird ein Plan im Tab "Behänge" zugewiesen.',
    },
    publicHolidayFederalState: { en: 'German federal state (for public holidays)', de: 'Bundesland (für Feiertage)' },
    publicHolidayFederalStateNone: { en: 'Disabled (no public holiday detection)', de: 'Deaktiviert (keine Feiertagserkennung)' },
    publicHolidayFederalStateBW: { en: 'Baden-Württemberg', de: 'Baden-Württemberg' },
    publicHolidayFederalStateBY: { en: 'Bavaria', de: 'Bayern' },
    publicHolidayFederalStateBE: { en: 'Berlin', de: 'Berlin' },
    publicHolidayFederalStateBB: { en: 'Brandenburg', de: 'Brandenburg' },
    publicHolidayFederalStateHB: { en: 'Bremen', de: 'Bremen' },
    publicHolidayFederalStateHH: { en: 'Hamburg', de: 'Hamburg' },
    publicHolidayFederalStateHE: { en: 'Hesse', de: 'Hessen' },
    publicHolidayFederalStateMV: { en: 'Mecklenburg-Vorpommern', de: 'Mecklenburg-Vorpommern' },
    publicHolidayFederalStateNI: { en: 'Lower Saxony', de: 'Niedersachsen' },
    publicHolidayFederalStateNW: { en: 'North Rhine-Westphalia', de: 'Nordrhein-Westfalen' },
    publicHolidayFederalStateRP: { en: 'Rhineland-Palatinate', de: 'Rheinland-Pfalz' },
    publicHolidayFederalStateSL: { en: 'Saarland', de: 'Saarland' },
    publicHolidayFederalStateSN: { en: 'Saxony', de: 'Sachsen' },
    publicHolidayFederalStateST: { en: 'Saxony-Anhalt', de: 'Sachsen-Anhalt' },
    publicHolidayFederalStateSH: { en: 'Schleswig-Holstein', de: 'Schleswig-Holstein' },
    publicHolidayFederalStateTH: { en: 'Thuringia', de: 'Thüringen' },
    areas: { en: 'Plans', de: 'Plan' },
    areaName: { en: 'Plan name', de: 'Planname' },
    weekdayOpen: { en: 'Weekday open (time, ±offset, or ±offset!cap)', de: 'Wochentag auf (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    weekdayClose: { en: 'Weekday close (time, ±offset, or ±offset!cap)', de: 'Wochentag zu (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    weekendOpen: { en: 'Weekend open (time, ±offset, or ±offset!cap)', de: 'Wochenende auf (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    weekendClose: { en: 'Weekend close (time, ±offset, or ±offset!cap)', de: 'Wochenende zu (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    holidayOpen: { en: 'Public holiday open (time, ±offset, or ±offset!cap)', de: 'Feiertag auf (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    holidayClose: { en: 'Public holiday close (time, ±offset, or ±offset!cap)', de: 'Feiertag zu (Uhrzeit, ±Versatz oder ±Versatz!Obergrenze)' },
    perWeekdayToggle: { en: 'Individual weekdays (optional overrides)', de: 'Einzelne Wochentage (optionale Überschreibung)' },
    perWeekdayHintText: {
        en: 'Override the open/close value for one specific weekday. Leave a field empty to keep using the weekday/weekend value above for that field.',
        de: 'Überschreibt den Öffnen-/Schließen-Wert für einen einzelnen Wochentag. Feld leer lassen, um für dieses Feld weiterhin den Wochentag-/Wochenende-Wert oben zu verwenden.',
    },
    weekdayOverrideOpen: { en: 'Open', de: 'Auf' },
    weekdayOverrideClose: { en: 'Close', de: 'Zu' },
    weekdayMonday: { en: 'Monday', de: 'Montag' },
    weekdayTuesday: { en: 'Tuesday', de: 'Dienstag' },
    weekdayWednesday: { en: 'Wednesday', de: 'Mittwoch' },
    weekdayThursday: { en: 'Thursday', de: 'Donnerstag' },
    weekdayFriday: { en: 'Friday', de: 'Freitag' },
    weekdaySaturday: { en: 'Saturday', de: 'Samstag' },
    weekdaySunday: { en: 'Sunday', de: 'Sonntag' },
    addAreaButton: { en: '+ Add plan', de: '+ Plan hinzufügen' },
    weather: { en: 'Weather data', de: 'Wetterdaten' },
    weatherHintText: {
        en: 'Configure the foreign state IDs of your own weather station here. Any value left empty disables the protection functions that need it (an external weather-service fallback is not implemented yet).',
        de: 'Hier werden die Fremd-State-IDs der eigenen Wetterstation eingetragen. Ein leer gelassener Wert deaktiviert die davon abhängigen Schutzfunktionen (ein externer Wetterdienst-Fallback ist noch nicht umgesetzt).',
    },
    weatherSolarRadiation: { en: 'Solar radiation (W/m²) state ID', de: 'Solarstrahlung (W/m²) State-ID' },
    weatherWindSpeed: { en: 'Wind speed (km/h) state ID', de: 'Windgeschwindigkeit (km/h) State-ID' },
    weatherRain: { en: 'Rain (boolean) state ID', de: 'Regen (boolean) State-ID' },
    weatherOutdoorTemp: { en: 'Outdoor temperature (°C) state ID', de: 'Außentemperatur (°C) State-ID' },
    weatherHumidity: { en: 'Humidity (%) state ID', de: 'Luftfeuchte (%) State-ID' },
    thresholds: { en: 'Global thresholds', de: 'Globale Schwellwerte' },
    sunCloseThreshold: { en: 'Sun close threshold (W/m²)', de: 'Sonnenschutz-Schließschwelle (W/m²)' },
    sunOpenThreshold: { en: 'Sun open threshold (W/m²)', de: 'Sonnenschutz-Öffnungsschwelle (W/m²)' },
    windOpenThreshold: { en: 'Wind activate threshold (km/h)', de: 'Windschutz-Auslöseschwelle (km/h)' },
    windCloseAllowedThreshold: { en: 'Wind calm threshold (km/h)', de: 'Windschutz-Ruheschwelle (km/h)' },
    frostThreshold: { en: 'Frost threshold (°C)', de: 'Frostschutz-Schwelle (°C)' },
    groups: { en: 'Groups', de: 'Gruppen' },
    groupsHintText: {
        en: 'Combine multiple coverings for joint control. Member IDs are entered as a comma-separated list of covering IDs.',
        de: 'Fasst mehrere Rolläden für eine gemeinsame Steuerung zusammen. Mitglieder-IDs werden als kommagetrennte Liste von Rolladen-IDs eingetragen.',
    },
    groupMemberIds: { en: 'Member covering IDs (comma-separated)', de: 'Mitglieder-Rolladen-IDs (kommagetrennt)' },
    addGroupButton: { en: '+ Add group', de: '+ Gruppe hinzufügen' },
    scenes: { en: 'Scenes', de: 'Szenen' },
    scenesHintText: {
        en: 'Named presets that drive one or more coverings to specific positions at once. Targets are entered as "coveringId:percent" pairs, comma-separated.',
        de: 'Benannte Vorgabepositionen, die mehrere Rolläden gleichzeitig auf bestimmte Positionen fahren. Ziele werden als kommagetrennte "coveringId:percent"-Paare eingetragen.',
    },
    sceneTargets: { en: 'Targets ("id:percent", comma-separated)', de: 'Ziele ("id:percent", kommagetrennt)' },
    addSceneButton: { en: '+ Add scene', de: '+ Szene hinzufügen' },
};
