/* eslint-disable */
// Translation dictionary for the custom (non-JSONConfig) admin settings page.
// Only "en" and "de" are maintained; all other languages fall back to "en".
systemDictionary = {
    'shutters adapter settings': { en: 'Adapter settings for shutters', de: 'Adaptereinstellungen für shutters' },
    shutters: { en: 'Coverings', de: 'Behänge' },
    shuttersHintText: {
        en: 'Configure your roller shutters, blinds and awnings here. Each card represents one covering; only the fields relevant to its selected system and enabled protection functions are shown.',
        de: 'Hier werden Rolläden, Raffstores und Markisen konfiguriert. Jede Karte repräsentiert einen Behang; es werden nur die Felder angezeigt, die für das gewählte System und die aktivierten Schutzfunktionen relevant sind.',
    },
    scanButtonLabel: { en: 'Scan for coverings', de: 'Nach Rolläden suchen' },
    scanHintText: {
        en: 'Scans connected adapter instances for foreign states with a covering-related role and presents every newly found covering below as a preview (already configured coverings are never proposed again). Homematic (including the "Verschluss" enum.functions Gewerk), KNX, Shelly, Zigbee and Zigbee2MQTT are detected with their matching system; everything else falls back to the generic drivers. Review/rename the candidates and uncheck any you do not want, then confirm - only then are they actually added, which changes the adapter configuration and restarts the adapter instance automatically.',
        de: 'Durchsucht verbundene Adapterinstanzen nach Fremd-States mit einer rolladenbezogenen Rolle und zeigt jeden neu gefundenen Rolladen unten als Vorschlag an (bereits konfigurierte Rolläden werden nie erneut vorgeschlagen). Homematic (inkl. des Gewerks "Verschluss"), KNX, Shelly, Zigbee und Zigbee2MQTT werden mit dem passenden System erkannt; alles andere fällt auf die generischen Driver zurück. Vorschläge prüfen/umbenennen und nicht gewünschte abwählen, dann bestätigen - erst dann werden sie tatsächlich hinzugefügt, was die Adapterkonfiguration ändert und die Adapterinstanz automatisch neu startet.',
    },
    applyScannedButton: { en: 'Add selected coverings', de: 'Ausgewählte Rolläden hinzufügen' },
    discardScanButton: { en: 'Discard', de: 'Verwerfen' },
    id: { en: 'ID', de: 'ID' },
    name: { en: 'Name', de: 'Name' },
    coveringName: { en: 'Designation', de: 'Bezeichnung' },
    coveringType: { en: 'Covering type', de: 'Behangtyp' },
    coveringTypeRolladen: { en: 'Roller shutter', de: 'Rolladen' },
    coveringTypeRaffstore: { en: 'External venetian blind', de: 'Raffstore' },
    coveringTypeMarkise: { en: 'Awning', de: 'Markise' },
    coveringTypeLamellen: { en: 'Vertical lamella blind', de: 'Lamellenvorhang' },
    driverType: { en: 'System', de: 'System' },
    driverTypeHomematic: { en: 'Homematic (hm-rpc/hm-rega)', de: 'Homematic (hm-rpc/hm-rega)' },
    driverTypeHmip: { en: 'Homematic IP Cloud (ioBroker.hmip)', de: 'Homematic IP Cloud (ioBroker.hmip)' },
    driverTypeKnx: { en: 'KNX', de: 'KNX' },
    driverTypeShelly: { en: 'Shelly (Cover mode)', de: 'Shelly (Cover-Modus)' },
    driverTypeZigbee: { en: 'Zigbee (ioBroker.zigbee)', de: 'Zigbee (ioBroker.zigbee)' },
    driverTypeZigbee2Mqtt: { en: 'Zigbee2MQTT', de: 'Zigbee2MQTT' },
    driverTypeTuya: { en: 'Tuya (ioBroker.tuya)', de: 'Tuya (ioBroker.tuya)' },
    driverTypeSomfy: { en: 'Somfy (ioBroker.tahoma)', de: 'Somfy (ioBroker.tahoma)' },
    driverTypeVelux: { en: 'Velux (KLF200/ioBroker.velux)', de: 'Velux (KLF200/ioBroker.velux)' },
    driverTypeEnocean: { en: 'EnOcean (ioBroker.enocean)', de: 'EnOcean (ioBroker.enocean)' },
    driverTypeVelbus: { en: 'Velbus (ioBroker.velbus)', de: 'Velbus (ioBroker.velbus)' },
    driverTypeLoxone: { en: 'Loxone (ioBroker.loxone)', de: 'Loxone (ioBroker.loxone)' },
    driverTypeHomey: { en: 'Homey', de: 'Homey' },
    driverTypeMqtt: { en: 'Generic MQTT cover', de: 'Generischer MQTT-Cover' },
    driverTypeGenericPosition: { en: 'Generic (position state)', de: 'Generisch (Positions-State)' },
    driverTypeGenericRelay: { en: 'Generic (open/close relay)', de: 'Generisch (Auf/Zu-Relais)' },
    area: { en: 'Plan', de: 'Plan' },
    schedulePlan: { en: 'Schedule', de: 'Zeitplan' },
    orientation: { en: 'Orientation (°, compass, 0=N/90=E/180=S/270=W)', de: 'Ausrichtung (°, Kompass, 0=N/90=O/180=S/270=W)' },
    automationEnabled: { en: 'Scheduled automation', de: 'Zeitautomatik' },
    invertPosition: { en: 'Invert position mapping', de: 'Positionszuordnung umkehren' },
    statePosition: {
        en: 'Position command state ID (0% open/raised; 100% closed/lowered)',
        de: 'Positions-Sollwert-State-ID (0 % geöffnet/angehoben; 100 % geschlossen/abgesenkt)',
    },
    statePositionActual: {
        en: 'Actual position state ID (0% open/raised; 100% closed/lowered)',
        de: 'Ist-Positions-State-ID (0 % geöffnet/angehoben; 100 % geschlossen/abgesenkt)',
    },
    statePositionInverted: {
        en: 'Position command state ID (0% closed/lowered; 100% open/raised)',
        de: 'Positions-Sollwert-State-ID (0 % geschlossen/abgesenkt; 100 % geöffnet/angehoben)',
    },
    statePositionActualInverted: {
        en: 'Actual position state ID (0% closed/lowered; 100% open/raised)',
        de: 'Ist-Positions-State-ID (0 % geschlossen/abgesenkt; 100 % geöffnet/angehoben)',
    },
    stateOpen: { en: 'Open state ID', de: 'Auf-State-ID' },
    stateClose: { en: 'Close state ID', de: 'Zu-State-ID' },
    stateStop: { en: 'Stop state ID', de: 'Stopp-State-ID' },
    stateControl: { en: 'Control state ID (open/close/stop DP)', de: 'Control-State-ID (Auf/Zu/Stopp-DP)' },
    stateTilt: { en: 'Tilt state ID (optional)', de: 'Kippwinkel-State-ID (optional)' },
    stateTiltActual: { en: 'Actual tilt state ID (optional)', de: 'Ist-Kippwinkel-State-ID (optional)' },
    stateUp: { en: 'Up state ID', de: 'Auf-Impuls-State-ID' },
    stateDown: { en: 'Down state ID', de: 'Ab-Impuls-State-ID' },
    statesSectionTitle: { en: 'Linked hardware', de: 'Verknüpfte Hardware' },
    protectionSectionTitle: { en: 'Protection settings', de: 'Automatikfunktionen' },
    sunProtectionHintText: {
        en: 'When "Orientation" above is set, the sun-window (when sun protection may apply) is derived from it: active whenever the current sun azimuth is within the tolerance below on either side of the orientation, e.g. a south-facing window (180°) with the default 70° tolerance is active for sun azimuths 110-250°. The window additionally requires the sun elevation to reach the minimum below (default 0° = above the horizon), and, if a maximum cloud cover is set, the sky to be clear enough (requires the cloud-cover state ID under Weather data). The sun window start/end fields are only used as a fallback when no orientation is set.',
        de: 'Wenn oben eine "Ausrichtung" gesetzt ist, wird das Sonnenschutz-Zeitfenster daraus abgeleitet: aktiv, solange der aktuelle Sonnenazimut innerhalb der unten stehenden Toleranz beidseitig der Ausrichtung liegt, z.B. ist ein nach Süden (180°) ausgerichtetes Fenster mit der Standardtoleranz von 70° für Sonnenazimute von 110-250° aktiv. Zusätzlich muss die Sonnenhöhe die unten stehende Mindesthöhe erreichen (Standard 0° = über dem Horizont), und, falls ein maximaler Bewölkungsgrad gesetzt ist, der Himmel entsprechend klar sein (benötigt die Bewölkungsgrad-State-ID unter Wetterdaten). Die Felder Sonnenschutz-Fenster Start/Ende werden nur als Fallback verwendet, wenn keine Ausrichtung gesetzt ist.',
    },
    sunProtectionEnabled: { en: 'Sun protection', de: 'Sonnenschutz' },
    sunTargetPercent: { en: 'Covering height', de: 'Behanghöhe' },
    sunProtectionMinTemp: {
        en: 'Sun protection min. temp. (°C, optional)',
        de: 'Sonnenschutz Mindesttemperatur (°C, optional)',
    },
    orientationToleranceMinusDeg: {
        en: 'Sun window tolerance, lower bound (°, relative to orientation)',
        de: 'Sonnenschutz-Toleranz, Untergrenze (°, relativ zur Ausrichtung)',
    },
    orientationTolerancePlusDeg: {
        en: 'Sun window tolerance, upper bound (°, relative to orientation)',
        de: 'Sonnenschutz-Toleranz, Obergrenze (°, relativ zur Ausrichtung)',
    },
    sunProtectionMinElevationDeg: {
        en: 'Sun window: minimum sun elevation (°, default 0)',
        de: 'Sonnenschutz-Fenster: minimale Sonnenhöhe (°, Standard 0)',
    },
    sunProtectionMaxCloudCoverPercent: {
        en: 'Sun window: maximum cloud cover (%, empty = ignore)',
        de: 'Sonnenschutz-Fenster: maximaler Bewölkungsgrad (%, leer = ignorieren)',
    },
    orientationToleranceTimeHintLabel: {
        en: 'Corresponds to about',
        de: 'Entspricht etwa',
    },
    orientationToleranceNoLocationHint: {
        en: 'Corresponding time unknown (no location configured in system.config).',
        de: 'Entsprechende Uhrzeit unbekannt (kein Standort in system.config konfiguriert).',
    },
    orientationToleranceNoTimeHint: {
        en: "Corresponding time: sun does not reach today's azimuth window at this orientation.",
        de: 'Entsprechende Uhrzeit: Sonne erreicht das Azimutfenster bei dieser Ausrichtung heute nicht.',
    },
    sunWindowStart: { en: 'Sun window start (fallback, no orientation set)', de: 'Sonnenschutz-Fenster Start (Fallback ohne Ausrichtung)' },
    sunWindowEnd: { en: 'Sun window end (fallback, no orientation set)', de: 'Sonnenschutz-Fenster Ende (Fallback ohne Ausrichtung)' },
    rainProtectionEnabled: { en: 'Rain protection', de: 'Regenschutz' },
    rainProtectionWindDirectionToleranceDeg: {
        en: 'Rain: wind-direction tolerance (±°, requires orientation)',
        de: 'Regenschutz: Windrichtungs-Toleranz (±°, benötigt Ausrichtung)',
    },
    windProtectionEnabled: { en: 'Wind protection', de: 'Windschutz' },
    frostProtectionEnabled: { en: 'Frost protection', de: 'Frostschutz' },
    nightCoolingEnabled: { en: 'Night cooling', de: 'Nachtauskühlung' },
    doorProtectionEnabled: { en: 'Door contact protection', de: 'Rolladensperre' },
    nightCoolingIndoorTempStateId: { en: 'Indoor temperature state ID', de: 'Innentemperatur-State-ID' },
    doorContactStateId: { en: 'Door contact state ID', de: 'Türkontakt-State-ID' },
    relayOpenRuntimeSecs: { en: 'Relay opening runtime (s)', de: 'Relais-Öffnungslaufzeit (s)' },
    relayCloseRuntimeSecs: { en: 'Relay closing runtime (s)', de: 'Relais-Schließlaufzeit (s)' },
    invertDoorContact: { en: 'Invert door contact', de: 'Türkontakt invertieren' },
    addCoveringButton: { en: '+ Add covering', de: '+ Rolladen hinzufügen' },
    removeButton: { en: 'Remove', de: 'Entfernen' },
    areasHintText: {
        en: 'Configure the daily opening/closing schedule per plan here. Pick a schedule mode: "All days the same" (a single open/close pair), "Weekday / weekend / public holiday" (the classic three-field schedule), or "Individual weekday + public holiday" (a separate open/close pair for each weekday, plus a public holiday override). Only the fields relevant to the selected mode are shown. Each open/close field is either a plain clock time ("HH:MM", 24h), an offset relative to sunrise (open) / sunset (close) written with a leading "+" (after) or "-" (before) sign as plain minutes (e.g. "-30") or an "HH:MM" duration (e.g. "+01:30") - append "d" (e.g. "-30d") to use civil dawn/dusk instead of the actual sunrise/sunset - or that offset combined with a "!HH:MM" cap time, e.g. "+30!19:00" (30 minutes after sunset, but never later than 19:00 - analogous for opening/sunrise). Leave a field empty to skip that action. Assign a plan to a covering on the Coverings tab.',
        de: 'Hier wird der tägliche Öffnen-/Schließen-Zeitplan pro Plan konfiguriert. Zunächst den Zeitplan-Modus wählen: "Alle Tage gleich" (ein einziges Auf-/Zu-Paar), "Wochentag / Wochenende / Feiertag" (der klassische Zeitplan mit drei Feldern) oder "Einzelne Wochentage + Feiertag" (ein eigenes Auf-/Zu-Paar für jeden Wochentag, plus Feiertagsüberschreibung). Es werden nur die für den gewählten Modus relevanten Felder angezeigt. Jedes Öffnen-/Schließen-Feld ist entweder eine feste Uhrzeit ("HH:MM", 24h), ein Versatz relativ zum Sonnenaufgang (Öffnen) bzw. Sonnenuntergang (Schließen) mit führendem "+" (danach) oder "-" (davor) als reine Minuten (z.B. "-30") oder als "HH:MM"-Dauer (z.B. "+01:30") - mit angehängtem "d" (z.B. "-30d") wird statt Sonnenaufgang/-untergang die Dämmerung verwendet - oder dieser Versatz kombiniert mit einer "!HH:MM"-Obergrenze, z.B. "+30!19:00" (30 Minuten nach Sonnenuntergang, spätestens jedoch 19:00 - sinngemäß auch für Öffnen/Sonnenaufgang). Feld leer lassen, um diese Aktion zu überspringen. Einem Behang wird ein Plan im Tab "Behänge" zugewiesen.',
    },
    holidayStateId: { en: 'Public holiday state ID', de: 'Feiertag-State-ID' },
    browseButton: { en: '... Browse', de: '... Durchsuchen' },
    pickerTitle: { en: 'Select a state', de: 'State auswählen' },
    pickerHintText: { en: 'Type at least 2 characters to search by ID or name, or browse the folder tree below.', de: 'Mindestens 2 Zeichen eingeben, um nach ID oder Name zu suchen, oder unten im Ordnerbaum blättern.' },
    pickerNoResultsText: { en: 'No matching states found.', de: 'Keine passenden States gefunden.' },
    pickerMoreResultsText: { en: '... and %d more - refine your search.', de: '... und %d weitere - Suche weiter eingrenzen.' },
    pickerBooleanOnlyLabel: { en: 'Boolean states only', de: 'Nur boolsche States' },
    pickerCancelButton: { en: 'Cancel', de: 'Abbrechen' },
    holidayHintText: {
        en: 'ID of an existing boolean state (own or foreign, e.g. from a calendar/iCal adapter) whose current value decides whether "today" counts as a public holiday for every plan below. true = public holiday, false/empty = not a public holiday. Leave empty to disable holiday-specific schedules entirely.',
        de: 'ID eines vorhandenen boolschen States (eigen oder fremd, z.B. von einem Kalender-/iCal-Adapter), dessen aktueller Wert entscheidet, ob "heute" für jeden Plan unten als Feiertag gilt. true = Feiertag, false/leer = kein Feiertag. Leer lassen, um feiertagsspezifische Zeitpläne komplett zu deaktivieren.',
    },
    icalAdapterInstance: { en: 'iCal adapter instance', de: 'iCal-Adapter-Instanz' },
    icalTitlePrefix: { en: 'iCal event title prefix', de: 'iCal-Termintitel-Präfix' },
    icalHintText: {
        en: 'Optionally override a single day\'s opening/closing time via an `ioBroker.ical` instance (configure the actual calendar URL/file there, not here). Add an event whose title starts with the prefix above, e.g. "Rolläden auf 07:00" (overrides today\'s opening time for every plan) or "Rolläden: Kinderzimmer auf 07:00" (only for the plan named "Kinderzimmer"); use "zu" instead of "auf" to override the closing time. Leave the instance field empty to disable this entirely.',
        de: 'Optional kann die Öffnen-/Schließen-Zeit für einen einzelnen Tag über eine `ioBroker.ical`-Instanz überschrieben werden (die eigentliche Kalender-URL/-Datei wird dort konfiguriert, nicht hier). Dazu einen Termin anlegen, dessen Titel mit dem obigen Präfix beginnt, z.B. "Rolläden auf 07:00" (überschreibt die heutige Öffnen-Zeit für jeden Plan) oder "Rolläden: Kinderzimmer auf 07:00" (nur für den Plan "Kinderzimmer"); "zu" statt "auf" für die Schließen-Zeit. Instanz-Feld leer lassen, um dies komplett zu deaktivieren.',
    },
    pushoverInstance: { en: 'Pushover instance', de: 'Pushover-Instanz' },
    telegramInstance: { en: 'Telegram instance', de: 'Telegram-Instanz' },
    thresholdsHintText: {
        en: 'Higher "close" thresholds mean the corresponding protection only reacts to stronger sun/wind, i.e. it activates less often. "Sun close/open" (W/m²) control sun protection (6.1): close activates it, open (lower, held for 10 minutes to avoid flickering when clouds pass) deactivates it again. "Trigger sun protection by cloud cover alone" is an optional addition (6.3, requires the cloud-cover state ID under Weather data): while enabled, sun protection also activates whenever cloud cover is at/below the "clear/mostly clear sky" percentage below, independent of the radiation reading - useful if radiation alone reacts too slowly or a sensor is unreliable. "Wind open/close-allowed" (km/h) work the same way for storm protection (7a): "open" is the speed storm protection engages at, "close-allowed" (lower, held for 10 minutes) is the calmer speed it must drop back below before normal operation resumes. "Frost threshold" (°C) is the outdoor temperature at/below which automated movement pauses if it is also damp/raining (7b). The night-cooling fields (7c) only apply to coverings with that feature explicitly enabled: the indoor temperature must reach the minimum, and be at least the configured amount warmer than outdoors, before a covering is kept open overnight instead of closing on schedule.',
        de: 'Höhere "Schließen"-Schwellwerte bedeuten, dass der jeweilige Schutz erst bei stärkerer Sonne/Wind reagiert, also seltener aktiv wird. "Sonnenschutz Schließen/Öffnen" (W/m²) steuern den Sonnenschutz (6.1): Schließen aktiviert ihn, Öffnen (niedriger, 10 Minuten gehalten gegen Flackern bei durchziehenden Wolken) deaktiviert ihn wieder. "Auslösung nur vom Grad der Bewölkung abhängig machen" ist eine optionale Ergänzung (6.3, benötigt die Bewölkungsgrad-State-ID unter Wetterdaten): ist diese Option aktiv, greift der Sonnenschutz zusätzlich immer dann, wenn der Bewölkungsgrad die untenstehende "klar/überwiegend klar"-Schwelle erreicht oder unterschreitet - unabhängig vom Strahlungswert. Sinnvoll, wenn die Strahlung allein zu langsam reagiert oder ein Sensor unzuverlässig ist. "Windschutz Öffnen/Schließen erlaubt" (km/h) funktionieren genauso für den Sturmschutz (7a): "Öffnen" ist die Geschwindigkeit, ab der der Sturmschutz eingreift, "Schließen erlaubt" (niedriger, 10 Minuten gehalten) die ruhigere Geschwindigkeit, auf die sie erst wieder sinken muss, bevor der Normalbetrieb weiterläuft. "Frostschutz-Schwelle" (°C) ist die Außentemperatur, bei/unter der automatische Fahrbefehle pausieren, sofern es zusätzlich feucht ist/regnet (7b). Die Nachtauskühlungs-Felder (7c) gelten nur für Rolläden, bei denen diese Funktion explizit aktiviert ist: die Innentemperatur muss das Minimum erreichen und mindestens um den eingestellten Betrag wärmer sein als draußen, bevor ein Rolladen nachts offen gehalten wird statt planmäßig zu schließen.',
    },
    notifyHintText: {
        en: 'Optionally send a notification via an existing `pushover`/`telegram` adapter instance (e.g. "pushover.0") when a covering\'s watchdog reports it is not responding, or when storm/frost protection engages or clears for at least one covering (one combined notification, not one per covering). Configure the recipient/chat directly on that instance, not here. Both fields can be left empty to disable notifications entirely; either or both can be set at once.',
        de: 'Optional kann eine Benachrichtigung über eine vorhandene `pushover`-/`telegram`-Adapterinstanz (z.B. "pushover.0") gesendet werden, wenn der Watchdog eines Rolladens meldet, dass er nicht reagiert, oder wenn Sturm-/Frostschutz für mindestens einen Rolladen aktiv wird bzw. endet (eine gesammelte Benachrichtigung, nicht eine je Rolladen). Empfänger/Chat wird direkt auf dieser Instanz konfiguriert, nicht hier. Beide Felder können leer gelassen werden, um Benachrichtigungen komplett zu deaktivieren; es kann auch nur eines oder beide gesetzt werden.',
    },
    areas: { en: 'Plans', de: 'Zeitpläne' },
    areaName: { en: 'Plan name', de: 'Planname' },
    scheduleMode: { en: 'Schedule mode', de: 'Zeitplan-Modus' },
    scheduleModeUniform: { en: 'All days the same', de: 'Alle Tage gleich' },
    scheduleModeWeekdayWeekend: { en: 'Weekday / weekend / public holiday', de: 'Wochentag / Wochenende / Feiertag' },
    scheduleModePerWeekday: { en: 'Individual weekday + public holiday', de: 'Einzelne Wochentage + Feiertag' },
    allDaysLabel: { en: 'All days', de: 'Alle Tage' },
    weekdayLabel: { en: 'Weekday', de: 'Wochentag' },
    weekendLabel: { en: 'Weekend', de: 'Wochenende' },
    perWeekdayHintText: {
        en: 'Set the open/close value for each individual weekday. Leave a field empty to skip that action on that weekday. The public holiday fields below apply on public holidays instead, falling back to the current weekday\'s value if left empty.',
        de: 'Hier wird der Öffnen-/Schließen-Wert für jeden einzelnen Wochentag festgelegt. Feld leer lassen, um diese Aktion an diesem Wochentag zu überspringen. An Feiertagen gelten stattdessen die Feiertagsfelder unten, die bei leerem Feld auf den Wert des aktuellen Wochentags zurückfallen.',
    },
    weekdayOverrideOpen: { en: 'Open', de: 'Auf' },
    weekdayOverrideClose: { en: 'Close', de: 'Zu' },
    weekdayMonday: { en: 'Monday', de: 'Montag' },
    weekdayTuesday: { en: 'Tuesday', de: 'Dienstag' },
    weekdayWednesday: { en: 'Wednesday', de: 'Mittwoch' },
    weekdayThursday: { en: 'Thursday', de: 'Donnerstag' },
    weekdayFriday: { en: 'Friday', de: 'Freitag' },
    weekdaySaturday: { en: 'Saturday', de: 'Samstag' },
    weekdaySunday: { en: 'Sunday', de: 'Sonntag' },
    weekdayHoliday: { en: 'Public holiday', de: 'Feiertag' },
    addAreaButton: { en: '+ Add plan', de: '+ Plan hinzufügen' },
    weather: { en: 'Weather data', de: 'Wetterdaten' },
    weatherHintText: {
        en: 'Configure the foreign state IDs of your own weather station here. Any value left empty disables the protection functions that need it (an external weather-service fallback is not implemented yet). Cloud cover is optional and only used by the "trigger by cloud cover alone" option under Global thresholds. Wind direction is optional and only used by a covering\'s own "Rain: wind-direction tolerance" field (shown once rain protection is enabled and an orientation is set for that covering). "Summer" state ID left empty: sun protection instead uses the heating-period dates below (both empty too = always summer, the original default).',
        de: 'Hier werden die Fremd-State-IDs der eigenen Wetterstation eingetragen. Ein leer gelassener Wert deaktiviert die davon abhängigen Schutzfunktionen (ein externer Wetterdienst-Fallback ist noch nicht umgesetzt). Der Grad der Bewölkung ist optional und wird nur von der Option "Auslösung nur vom Grad der Bewölkung abhängig machen" unter Globale Schwellwerte verwendet. Die Windrichtung ist optional und wird nur vom Feld "Regenschutz: Windrichtungs-Toleranz" einer einzelnen Rolladen-Karte verwendet (erscheint, sobald Regenschutz aktiviert und eine Ausrichtung gesetzt ist). "Sommer"-State-ID leer gelassen: der Sonnenschutz nutzt dann stattdessen die Heizperioden-Daten unten (auch beide leer = immer Sommer, der ursprüngliche Standard).',
    },
    weatherSolarRadiation: { en: 'Solar radiation (W/m²) state ID', de: 'Solarstrahlung (W/m²) State-ID' },
    weatherWindSpeed: { en: 'Wind speed (km/h) state ID', de: 'Windgeschwindigkeit (km/h) State-ID' },
    weatherRain: { en: 'Rain (boolean) state ID', de: 'Regen (boolean) State-ID' },
    weatherOutdoorTemp: { en: 'Outdoor temperature (°C) state ID', de: 'Außentemperatur (°C) State-ID' },
    weatherHumidity: { en: 'Humidity (%) state ID', de: 'Luftfeuchte (%) State-ID' },
    weatherIsSummer: { en: 'Summer mode (boolean) state ID', de: 'Sommermodus (boolean) State-ID' },
    weatherCloudCover: { en: 'Cloud cover (%) state ID', de: 'Grad der Bewölkung (%) State-ID' },
    weatherWindDirection: { en: 'Wind direction (°) state ID', de: 'Windrichtung (°) State-ID' },
    heatingPeriodStart: {
        en: 'Heating period start (MM-DD, e.g. 10-15) - fallback if summer state ID above is empty',
        de: 'Heizperiode Beginn (MM-TT, z.B. 10-15) - Fallback, wenn obige Sommer-State-ID leer ist',
    },
    heatingPeriodEnd: {
        en: 'Heating period end (MM-DD, e.g. 04-15)',
        de: 'Heizperiode Ende (MM-TT, z.B. 04-15)',
    },
    thresholds: { en: 'Global thresholds', de: 'Globale Schwellwerte' },
    sunProtectionGlobalEnabled: { en: 'Sun protection globally enabled', de: 'Sonnenschutz global aktiviert' },
    sunCloseThreshold: { en: 'Sun close threshold (W/m²)', de: 'Sonnenschutz-Schließschwelle (W/m²)' },
    sunOpenThreshold: { en: 'Sun open threshold (W/m²)', de: 'Sonnenschutz-Öffnungsschwelle (W/m²)' },
    sunProtectionCloudCoverTriggerEnabled: {
        en: 'Trigger sun protection by cloud cover alone',
        de: 'Auslösung nur vom Grad der Bewölkung abhängig machen',
    },
    sunProtectionClearSkyCloudCoverMaxPercent: {
        en: 'Clear/mostly clear sky threshold (cloud cover %)',
        de: 'Schwelle klarer/überwiegend klarer Himmel (Bewölkungsgrad %)',
    },
    windOpenThreshold: { en: 'Wind activate threshold (km/h)', de: 'Windschutz-Auslöseschwelle (km/h)' },
    windCloseAllowedThreshold: { en: 'Wind calm threshold (km/h)', de: 'Windschutz-Ruheschwelle (km/h)' },
    frostThreshold: { en: 'Frost threshold (°C)', de: 'Frostschutz-Schwelle (°C)' },
    nightCoolingIndoorMinTemp: { en: 'Night cooling indoor min. temp. (°C)', de: 'Nachtauskühlung Innentemp.-Min. (°C)' },
    nightCoolingMinDelta: { en: 'Night cooling min. indoor/outdoor delta (°C)', de: 'Nachtauskühlung Min.-Differenz innen/außen (°C)' },
    groups: { en: 'Groups', de: 'Gruppen' },
    groupsHintText: {
        en: 'Combine configured coverings for joint control. Select all members of the group below.',
        de: 'Fasst konfigurierte Rolläden für eine gemeinsame Steuerung zusammen. Unten alle Mitglieder der Gruppe auswählen.',
    },
    groupMemberIds: { en: 'Member coverings', de: 'Mitglieder-Rolläden' },
    addGroupButton: { en: '+ Add group', de: '+ Gruppe hinzufügen' },
    scenes: { en: 'Scenes', de: 'Szenen' },
    scenesHintText: {
        en: 'Named presets that drive one or more coverings to specific positions at once. Position values use 0% = fully open/raised and 100% = fully closed/lowered. Add one target row for each covering.',
        de: 'Benannte Vorgabepositionen, die mehrere Rolläden gleichzeitig auf bestimmte Positionen fahren. Positionswerte verwenden 0 % = vollständig geöffnet/angehoben und 100 % = vollständig geschlossen/abgesenkt. Für jeden Rolladen eine Zielzeile hinzufügen.',
    },
    sceneTargets: { en: 'Scene targets', de: 'Szenenziele' },
    sceneTargetCovering: { en: 'Covering', de: 'Rolladen' },
    sceneTargetPosition: {
        en: 'Target position (0% open/raised; 100% closed/lowered)',
        de: 'Zielposition (0 % geöffnet/angehoben; 100 % geschlossen/abgesenkt)',
    },
    addSceneTargetButton: { en: '+ Add target', de: '+ Ziel hinzufügen' },
    removeSceneTargetButton: { en: 'Remove target', de: 'Ziel entfernen' },
    missingCovering: { en: 'Missing covering', de: 'Fehlender Rolladen' },
    addSceneButton: { en: '+ Add scene', de: '+ Szene hinzufügen' },
    homematicLevelNormalized: { en: 'Homematic level uses 0-1', de: 'Homematic-Level verwendet 0-1' },
    rainTargetPercent: { en: 'Rain protection target position', de: 'Regenschutz-Zielposition' },
    maxRuntimeSecs: { en: 'Maximum runtime (s)', de: 'Maximale Laufzeit (s)' },
    minCommandIntervalMs: { en: 'Minimum command interval (ms)', de: 'Mindestabstand zwischen Befehlen (ms)' },
    weekdayOpen: { en: 'Weekday open', de: 'Wochentag auf' },
    weekdayClose: { en: 'Weekday close', de: 'Wochentag zu' },
    weekendOpen: { en: 'Weekend open', de: 'Wochenende auf' },
    weekendClose: { en: 'Weekend close', de: 'Wochenende zu' },
    holidayOpen: { en: 'Public holiday open', de: 'Feiertag auf' },
    holidayClose: { en: 'Public holiday close', de: 'Feiertag zu' },
    weekdayMondayOpen: { en: 'Monday open', de: 'Montag auf' },
    weekdayMondayClose: { en: 'Monday close', de: 'Montag zu' },
    weekdayTuesdayOpen: { en: 'Tuesday open', de: 'Dienstag auf' },
    weekdayTuesdayClose: { en: 'Tuesday close', de: 'Dienstag zu' },
    weekdayWednesdayOpen: { en: 'Wednesday open', de: 'Mittwoch auf' },
    weekdayWednesdayClose: { en: 'Wednesday close', de: 'Mittwoch zu' },
    weekdayThursdayOpen: { en: 'Thursday open', de: 'Donnerstag auf' },
    weekdayThursdayClose: { en: 'Thursday close', de: 'Donnerstag zu' },
    weekdayFridayOpen: { en: 'Friday open', de: 'Freitag auf' },
    weekdayFridayClose: { en: 'Friday close', de: 'Freitag zu' },
    weekdaySaturdayOpen: { en: 'Saturday open', de: 'Samstag auf' },
    weekdaySaturdayClose: { en: 'Saturday close', de: 'Samstag zu' },
    weekdaySundayOpen: { en: 'Sunday open', de: 'Sonntag auf' },
    weekdaySundayClose: { en: 'Sunday close', de: 'Sonntag zu' },
    sunOpenMinDurationMs: { en: 'Sun opening delay (ms)', de: 'Sonnenschutz-Öffnungsverzögerung (ms)' },
    windCalmMinDurationMs: { en: 'Wind calm delay (ms)', de: 'Windschutz-Ruheverzögerung (ms)' },
    automationTickMs: { en: 'Automation interval (ms)', de: 'Automatikintervall (ms)' },
    notifications: { en: 'Notifications', de: 'Benachrichtigungen' },
};
